### ISSUE TITLE
Show variable type on hover

### ISSUE THREAD

**Issue by db4** [hackwaly/vscode-ocaml#26]
From VS Code 1.3.0 release notes:

> **Show variable type on hover:** If a debug adapter returns the optional type attribute for the [variable type](https://github.com/Microsoft/vscode-debugadapter-node/blob/master/protocol/src/debugProtocol.ts#L741), VS Code will show the value of this attribute when hovering over the variable's name.

Can we support this?

**Comment by hackwaly** [comment]
Sure! I'm downloading new version of VS Code now.

**Comment by hackwaly** [comment]
I can't get it work, even I set `type?` property. Seems `variableRequest` can't directly response a variable with type, but can response a variable with sub-variables that has type. Maybe it's a bug of new version of DebugProtocol. https://github.com/Microsoft/vscode-debugadapter-node/blob/master/protocol/src/debugProtocol.ts#L575

Are there any screenshots about showing variable type? Or there is an extension implemented this feature? https://github.com/Microsoft/vscode-debugadapter-node/issues/32

**Comment by hackwaly** [comment]
I consider close this issue because of ocamldebug only gives us the type of result variable self per `display` command, which is useless. Otherwise we need issue lots of `display` commands to retrieve type informations of result's children (or call member or property). 

I implemented the simpler one in https://github.com/hackwaly/vscode-ocaml/commit/046ee31a5115410f7c8f69c1b76c803a92f47616, and it will release in v0.5.0.

**Comment by db4** [comment]
> I consider close this issue because of ocamldebug only gives us the type of result variable self per `display` command, which is useless.

When you issue `print` command it responds with
`<variable name> : <type> = <value>`
You are parsing this anyway and can use `<type>` info as well.

**Comment by hackwaly** [comment]
Yes, I did it in v0.5.0 which is released.

**Comment by db4** [comment]
> Yes, I did it in v0.5.0 which is released.

Hmm, I still don't see types in the debugger. E.g. for a record type a see `<record>` instead of the real type name. Maybe I should adjust some setting?

**Comment by hackwaly** [comment]
It's hidden by default in vscode. 

Said https://code.visualstudio.com/updates/June_2016

> Show Variable Type on Hover
> If a debug extension supports variable types, we now show the type when hovering over the variable name.

![image](https://cloud.githubusercontent.com/assets/540298/17510919/83bd03d6-5e53-11e6-8fef-6515416e20dc.png)

**Comment by hackwaly** [comment]
Eh... found a bug: it shows array as list.

**Comment by hackwaly** [comment]
Maybe showing type instead of `<record>` being there is better.

**Comment by db4** [comment]
Ah, I see. Yes, it works when hovering over a variable in the watch window. But I expected it to work in an  editor window also:

![image](https://cloud.githubusercontent.com/assets/6112699/17511549/0f3a385c-5e2c-11e6-9066-4884ef60f4b4.png)

**Comment by db4** [comment]
This commit https://github.com/hackwaly/vscode-ocaml/commit/cb8d50b0c6d29ff3d1ddf03a251644082f7618f4 breaks hovering over plain variables: instead of the variable's value its type is shown now.

**Comment by hackwaly** [comment]
Sorry, my mistake. Fixed in https://github.com/hackwaly/vscode-ocaml/commit/365f23cd6341f1948b7cfe774a60f24842957092.

**Comment by db4** [comment]
Now it's OK. Thanks!
